#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MobileRef.Pagination.Android.Resource", IsApplication=true)]

namespace MobileRef.Pagination.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::MobileRef.Pagination.Android.Resource.String.library_name;
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::MobileRef.Pagination.Android.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::MobileRef.Pagination.Android.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::MobileRef.Pagination.Android.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::MobileRef.Pagination.Android.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::MobileRef.Pagination.Android.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::MobileRef.Pagination.Android.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::MobileRef.Pagination.Android.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::MobileRef.Pagination.Android.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::MobileRef.Pagination.Android.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::MobileRef.Pagination.Android.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::MobileRef.Pagination.Android.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::MobileRef.Pagination.Android.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::MobileRef.Pagination.Android.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::MobileRef.Pagination.Android.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::MobileRef.Pagination.Android.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::MobileRef.Pagination.Android.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::MobileRef.Pagination.Android.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::MobileRef.Pagination.Android.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::MobileRef.Pagination.Android.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::MobileRef.Pagination.Android.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::MobileRef.Pagination.Android.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::MobileRef.Pagination.Android.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::MobileRef.Pagination.Android.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::MobileRef.Pagination.Android.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::MobileRef.Pagination.Android.Resource.Styleable.ProgressWheel_ahTextSize;
			global::PullToRefresharp.Resource.Attribute.contentViewId = global::MobileRef.Pagination.Android.Resource.Attribute.contentViewId;
			global::PullToRefresharp.Resource.Attribute.fastScrollThumbWidth = global::MobileRef.Pagination.Android.Resource.Attribute.fastScrollThumbWidth;
			global::PullToRefresharp.Resource.Attribute.headerIconDrawable = global::MobileRef.Pagination.Android.Resource.Attribute.headerIconDrawable;
			global::PullToRefresharp.Resource.Attribute.headerId = global::MobileRef.Pagination.Android.Resource.Attribute.headerId;
			global::PullToRefresharp.Resource.Attribute.headerTextColor = global::MobileRef.Pagination.Android.Resource.Attribute.headerTextColor;
			global::PullToRefresharp.Resource.Attribute.ptrHeaderBackground = global::MobileRef.Pagination.Android.Resource.Attribute.ptrHeaderBackground;
			global::PullToRefresharp.Resource.Attribute.pullDownProgressIndicatorId = global::MobileRef.Pagination.Android.Resource.Attribute.pullDownProgressIndicatorId;
			global::PullToRefresharp.Resource.Attribute.pullDownTension = global::MobileRef.Pagination.Android.Resource.Attribute.pullDownTension;
			global::PullToRefresharp.Resource.Attribute.pullEnabled = global::MobileRef.Pagination.Android.Resource.Attribute.pullEnabled;
			global::PullToRefresharp.Resource.Attribute.pullToRefreshText = global::MobileRef.Pagination.Android.Resource.Attribute.pullToRefreshText;
			global::PullToRefresharp.Resource.Attribute.refreshingText = global::MobileRef.Pagination.Android.Resource.Attribute.refreshingText;
			global::PullToRefresharp.Resource.Attribute.releaseToRefreshText = global::MobileRef.Pagination.Android.Resource.Attribute.releaseToRefreshText;
			global::PullToRefresharp.Resource.Attribute.snapbackDuration = global::MobileRef.Pagination.Android.Resource.Attribute.snapbackDuration;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_end = global::MobileRef.Pagination.Android.Resource.Color.ptrsharp_sb_gradient_end;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_start = global::MobileRef.Pagination.Android.Resource.Color.ptrsharp_sb_gradient_start;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_header_text = global::MobileRef.Pagination.Android.Resource.Color.ptrsharp_sb_header_text;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_header_text_shadow = global::MobileRef.Pagination.Android.Resource.Color.ptrsharp_sb_header_text_shadow;
			global::PullToRefresharp.Resource.Dimension.fastscroll_thumb_width = global::MobileRef.Pagination.Android.Resource.Dimension.fastscroll_thumb_width;
			global::PullToRefresharp.Resource.Drawable.progress_medium_holo = global::MobileRef.Pagination.Android.Resource.Drawable.progress_medium_holo;
			global::PullToRefresharp.Resource.Drawable.ptrsharp_serious_business_gradient = global::MobileRef.Pagination.Android.Resource.Drawable.ptrsharp_serious_business_gradient;
			global::PullToRefresharp.Resource.Drawable.serious_business_arrow = global::MobileRef.Pagination.Android.Resource.Drawable.serious_business_arrow;
			global::PullToRefresharp.Resource.Drawable.serious_business_arrow2 = global::MobileRef.Pagination.Android.Resource.Drawable.serious_business_arrow2;
			global::PullToRefresharp.Resource.Drawable.spinner_20_inner_holo = global::MobileRef.Pagination.Android.Resource.Drawable.spinner_20_inner_holo;
			global::PullToRefresharp.Resource.Drawable.spinner_20_outer_holo = global::MobileRef.Pagination.Android.Resource.Drawable.spinner_20_outer_holo;
			global::PullToRefresharp.Resource.Id.header = global::MobileRef.Pagination.Android.Resource.Id.header;
			global::PullToRefresharp.Resource.Id.header_container = global::MobileRef.Pagination.Android.Resource.Id.header_container;
			global::PullToRefresharp.Resource.Id.icon = global::MobileRef.Pagination.Android.Resource.Id.icon;
			global::PullToRefresharp.Resource.Id.pullDownProgressIndicator = global::MobileRef.Pagination.Android.Resource.Id.pullDownProgressIndicator;
			global::PullToRefresharp.Resource.Id.text = global::MobileRef.Pagination.Android.Resource.Id.text;
			global::PullToRefresharp.Resource.Layout.ptrsharp_header = global::MobileRef.Pagination.Android.Resource.Layout.ptrsharp_header;
			global::PullToRefresharp.Resource.String.library_name = global::MobileRef.Pagination.Android.Resource.String.library_name;
			global::PullToRefresharp.Resource.String.ptrsharp_pull_to_refresh = global::MobileRef.Pagination.Android.Resource.String.ptrsharp_pull_to_refresh;
			global::PullToRefresharp.Resource.String.ptrsharp_refreshing = global::MobileRef.Pagination.Android.Resource.String.ptrsharp_refreshing;
			global::PullToRefresharp.Resource.String.ptrsharp_release_to_refresh = global::MobileRef.Pagination.Android.Resource.String.ptrsharp_release_to_refresh;
			global::PullToRefresharp.Resource.Style.HoloProgressMedium = global::MobileRef.Pagination.Android.Resource.Style.HoloProgressMedium;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_contentViewId = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_contentViewId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_fastScrollThumbWidth = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_fastScrollThumbWidth;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerId = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_headerId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerTextColor = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_headerTextColor;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownTension = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_pullDownTension;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullEnabled = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_pullEnabled;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_refreshingText = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_refreshingText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration = global::MobileRef.Pagination.Android.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ahBarColor = 2130771984;
			
			// aapt resource value: 0x7f010018
			public const int ahBarLength = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int ahBarWidth = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int ahCircleColor = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int ahDelayMillis = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int ahRadius = 2130771990;
			
			// aapt resource value: 0x7f010011
			public const int ahRimColor = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int ahRimWidth = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int ahSpinSpeed = 2130771987;
			
			// aapt resource value: 0x7f01000d
			public const int ahText = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int ahTextColor = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int ahTextSize = 2130771983;
			
			// aapt resource value: 0x7f010001
			public const int contentViewId = 2130771969;
			
			// aapt resource value: 0x7f01000c
			public const int fastScrollThumbWidth = 2130771980;
			
			// aapt resource value: 0x7f01000a
			public const int headerIconDrawable = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int headerId = 2130771968;
			
			// aapt resource value: 0x7f010009
			public const int headerTextColor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int ptrHeaderBackground = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int pullDownProgressIndicatorId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int pullDownTension = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int pullEnabled = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int pullToRefreshText = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int refreshingText = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int releaseToRefreshText = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int snapbackDuration = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int ptrsharp_sb_gradient_end = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int ptrsharp_sb_gradient_start = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ptrsharp_sb_header_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ptrsharp_sb_header_text_shadow = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int fastscroll_thumb_width = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_errorstatus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_successstatus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int progress_medium_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ptrsharp_serious_business_gradient = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int roundedbg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int roundedbgdark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int serious_business_arrow = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int serious_business_arrow2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int spinner_20_inner_holo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int spinner_20_outer_holo = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int btnSearch = 2131230723;
			
			// aapt resource value: 0x7f08000a
			public const int header = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int header_container = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int icon = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int loadingImage = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int loadingProgressBar = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int loadingProgressWheel = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int lstArticles = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int pullDownProgressIndicator = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int text = 2131230733;
			
			// aapt resource value: 0x7f080006
			public const int textViewStatus = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int txtDescription = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int txtSearch = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ArticleCell = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ArticleTable = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loading = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loadingimage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loadingprogress = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ptrsharp_header = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060005
			public const int app_name = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int hello = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ptrsharp_pull_to_refresh = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int ptrsharp_refreshing = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ptrsharp_release_to_refresh = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int HoloProgressMedium = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[]
			{
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			public static int[] PullToRefresharpWrapper = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public const int PullToRefresharpWrapper_contentViewId = 1;
			
			// aapt resource value: 12
			public const int PullToRefresharpWrapper_fastScrollThumbWidth = 12;
			
			// aapt resource value: 10
			public const int PullToRefresharpWrapper_headerIconDrawable = 10;
			
			// aapt resource value: 0
			public const int PullToRefresharpWrapper_headerId = 0;
			
			// aapt resource value: 9
			public const int PullToRefresharpWrapper_headerTextColor = 9;
			
			// aapt resource value: 8
			public const int PullToRefresharpWrapper_ptrHeaderBackground = 8;
			
			// aapt resource value: 2
			public const int PullToRefresharpWrapper_pullDownProgressIndicatorId = 2;
			
			// aapt resource value: 4
			public const int PullToRefresharpWrapper_pullDownTension = 4;
			
			// aapt resource value: 11
			public const int PullToRefresharpWrapper_pullEnabled = 11;
			
			// aapt resource value: 5
			public const int PullToRefresharpWrapper_pullToRefreshText = 5;
			
			// aapt resource value: 7
			public const int PullToRefresharpWrapper_refreshingText = 7;
			
			// aapt resource value: 6
			public const int PullToRefresharpWrapper_releaseToRefreshText = 6;
			
			// aapt resource value: 3
			public const int PullToRefresharpWrapper_snapbackDuration = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
